apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ace
  name: myintegration-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ace
    spec:
      containers:
        - env:
            - name: LICENSE
              value: accept
            - name: ACE_SERVER_NAME
              value: ACESERVER
          name: myintegration-deployment
          image: us.gcr.io/kubernetes-cluster-234508/myapi:1.0
