apiVersion: v1
kind: Service
metadata:
  name: myintegration-service
  labels:
    app: myintegration-service
spec:
  type: NodePort
  ports:
    - port: 7600
      targetPort: 7600
      protocol: TCP
      name: webui
    - port: 7800
      targetPort: 7800
      protocol: TCP
      name: ace-http
    - port: 7843
      targetPort: 7843
      protocol: TCP
      name: ace-https
  selector:
    app: ace
